# Generated by Django 4.2.7 on 2023-12-18 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_categories_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, null=django.db.models.deletion.CASCADE),
            preserve_default=django.db.models.deletion.CASCADE,
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, null=django.db.models.deletion.CASCADE),
            preserve_default=django.db.models.deletion.CASCADE,
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.PositiveBigIntegerField(null=django.db.models.deletion.CASCADE),
            preserve_default=django.db.models.deletion.CASCADE,
        ),
    ]
